### ISSUE TITLE
Detect Error 429 and give a user-comprehensible description 

### ISSUE THREAD

**Issue by PatrickLerner** [tginfo/sticker-importer#3]
It seems to me that the app recently became broken and does not allow import of stickers anymore with the above error being returned. I tried multiple URLs and always found this result.

**Comment by Sominemo** [comment]
Could you share the URLs? Works on my side.

**Comment by PatrickLerner** [comment]
Thank you for the hint, I did not investigate if it might be something unrelated to the app itself. Here is the error I get with some random pack from the popular list:

| url | error |
|:-:|:-:|
| ![Screenshot_20220702-010000](https://user-images.githubusercontent.com/1738261/176976172-31cc65d8-bb45-404a-98ac-3b96668b0af7.png) | ![Screenshot_20220702-010007](https://user-images.githubusercontent.com/1738261/176976177-c4f62be2-1e49-4537-8081-e4d21ce9f517.png) |

I just tested it just now with me being connected to a VPN (before it was wireless network in Germany) and it seems to work. So maybe it is some issue either on VK side or my provider blocking something. As it works with VPN I will close it here since it does not seem like there is a bug with the app.

Thanks for the hint.

**Comment by Sominemo** [comment]
I would keep the issue open for now because I want to investigate. VK might be A/B testing something right now, so you may be getting different results under different IPs. I can prepare a build that will collect logs if you don't mind installing and running it.

**Comment by PatrickLerner** [comment]
Sure thing no problem. Just ping me and I can provide what you might need.

**Comment by Sominemo** [comment]
> Sure thing no problem. Just ping me and I can provide what you might need.

Please try importing stickers with the build attached (The APK is inside the ZIP). 

After getting the error, return to the main screen and press "Save Logs". The log file will be saved to your Downloads folder. You can attach it right here in this issue, it does not contain any sensitive data.

[me.tginfo.stickerimport.z.fat.apk.zip](https://github.com/tginfo/sticker-importer/files/9032175/me.tginfo.stickerimport.z.fat.apk.zip)

**Comment by PatrickLerner** [comment]
I attached you the file here: [tginfo_log_1.txt](https://github.com/tginfo/sticker-importer/files/9033576/tginfo_log_1.txt)

**Comment by Sominemo** [comment]
I see VK is returning Error 429: "You're requesting a lot!". 

I'll try to find an alternative method for getting the pack ID to see if we can circumvent this error.

**Comment by Sominemo** [comment]
Closed in ac580e352476b5af82b5fdd1bd2ffac2efd13e1b
